services:
  - type: web
    name: rsa-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    env: python
    plan: free
    autoDeploy: true
    region: oregon
